### ISSUE TITLE
Composer 2

### ISSUE THREAD

**Issue by Raruto** [raffaelj/cpmp-lib-skeleton#1]
Hi Raffael,

following the [composer and docker](https://github.com/raffaelj/cpmp-lib-skeleton/tree/3387f9897ff656901c5c35bf30d1524bbb547e97#via-composer-and-docker) installation i got the following warning coming from the [CpMultiplane](https://github.com/raffaelj/CpMultiplane/blob/ce7ffbf3be34a3995ca53ffd8d946162ec92d1a2/composer.json#L18) plugin:

> The "[oomphinc/composer-installers-extender](https://github.com/oomphinc/composer-installers-extender)" plugin was skipped because it requires a Plugin API version ("^1.0") that do
es not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Warning: You forced the install of 1.10.17 via --1, but 2.0.7 is the latest stable version. Updating to it via composer
self-update --stable is recommended.

Any plans regard uptading oomphinc's plugin to version 2? 

If needed, here's how to switch between composer versions:

```
composer self-update --1
```

```
composer self-update --2
```

**Comment by raffaelj** [comment]
I'm on openSUSE Tumbleweed and the [latest](https://software.opensuse.org/package/php-composer) official composer version is 1.10.16. This is why I still used the old one.

Thanks for the hint. `sudo composer self-update --2` did the trick, but eventually it will downgrade again after the next system update...

And composer 2.x has a few more events, that weren't available in 1.x. Maybe I can replace the `post-autoload-dump` now with more precise events...

Let me do some tests first. But of course I'm always open to keep software up to date. Hopefully I find some time next week.

**Comment by Raruto** [comment]
Ok, thanks for the note.

From what can I see [here](https://github.com/oomphinc/composer-installers-extender/blob/8d3fe38a1723e0e91076920c8bb946b1696e28ca/composer.json#L24), the latest release of **oomphinc/composer-installers-extender** should be compatible with both versions of composer.

_Have a nice Day,
Raruto_

**Comment by raffaelj** [comment]
I updated the composer-installers-extender dependency in CpMultiplane to ^2.0, but I have to do [some work][1] before I can release CpMultiplane 0.3.0 and than cpmp-lib-skeleton 0.1.1. So right now, the update only works if you require `"raffaelj/cpmultiplane": "dev-master"` in your `composer.json`.

[1]: https://github.com/raffaelj/CpMultiplane/issues/29

**Comment by raffaelj** [comment]
I created a new branch `composer2`, so installing this skeleton should work without error messsages and with dependencies in the right places again.

```
composer create-project --ignore-platform-reqs raffaelj/cpmp-lib-skeleton:dev-composer2 .
```
